services:
  postgres:
    image: postgres:18
    container_name: smarttasks-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-smart}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smart}
      POSTGRES_DB: ${POSTGRES_DB:-smarttasks}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  minio:
    image: minio/minio
    container_name: smarttasks-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
