spring:
  application:
    name: smarttasks
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:smarttasks}
    username: ${POSTGRES_USER:smart}
    password: ${POSTGRES_PASSWORD:smart}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${GOOGLE_ISSUER_URI:https://accounts.google.com}
minio:
  url: ${MINIO_URL:http://localhost:9000}
  accessKey: ${MINIO_ROOT_USER:admin}
  secretKey: ${MINIO_ROOT_PASSWORD:password}
  bucketName: ${MINIO_BUCKET:smarttasks}